spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/word_train
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,logfile
  endpoint:
    health:
      show-details: always
  info:
    # Включает информацию о приложении из application.yml
    env:
      enabled: true
    # Включает информацию о git, собранную плагином
    git:
      mode: "full"
logging:
  file:
    name: "./logs/log-file.log"

info:
  app:
    version: @project.version@
    author: lenu
    description: This is a multiuser anki training system
